name: CI Java (FortePix)
on: [push, pull_request]
jobs:
  test-java:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-java
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn -q -B -e -DskipTests=false test package
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: fortepix-java-jar
          path: backend-java/target/*.jar
