name: CI Python (FortePix)
on: [push, pull_request]
jobs:
  test-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-python
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pytest -q
